name: Deploy to Swarm (Docker Swarm)

on:
  push:
    branches:
      - main

env:
  DOCKER_HOST: tcp://<ip-address-of-your-swarm-manager>:2376
  DOCKER_REGISTRY_USER: <username>
  DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: <registry-username>/<image-name>:${{ env.GITHUB_SHA }}
        username: ${{ env.DOCKER_REGISTRY_USER }}
        password: ${{ env.DOCKER_REGISTRY_PASS }}

    - name: Deploy to swarm
      run: |
        echo "$DOCKER_REGISTRY_PASS" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
        docker stack deploy -c stack.yaml <stack-name>
      env:
        DOCKER_HOST: ${{ env.DOCKER_HOST }}
        DOCKER_TLS_CERTDIR: "/certs"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
        

        
